

server:
  port: 8081

spring:
  application:
    name: auth
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: postgres
    password: strongpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  jwt:
    access-token-expiration: 86400 # 24 hours
    refresh-token-expiration: 172800
    issuer: mentor-platform
