

server:
  port: 8081

spring:
  application:
    name: auth
  datasource:
    url: jdbc:postgresql://localhost:5432/taskTracker
    username: root
    password: qwe
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  jwt:
    access-token-expiration: 17280 # 24 hours
    issuer: mentor-platform
    secret: NR2i2fMCrZMI/QcQw+m3jqYFxCdAna6FaZpfHQBo+c0=

